apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  namespace: sample-ns
spec:
  containers:
  - name: nginx-1
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 200Mi
        cpu: 250m
      limits:
        memory: 250Mi
        cpu: 300m
