apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: p1
    environment: Dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    