apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-1

managedNodeGroups:
  - name: cluster-ng-1
    instanceTypes: [t3.micro]
    desiredCapacity: 2
    spot: true
